### ISSUE TITLE
大神遇到问题了，帮忙看看呗

### ISSUE THREAD

**Issue by Dangerous-LYQ** [LiMingYuGuang/typecho-theme-material#13]
![image](https://user-images.githubusercontent.com/22229047/31017269-83cb1fee-a55a-11e7-9ea0-2b17afeaa1c6.png)

![image](https://user-images.githubusercontent.com/22229047/31017199-5da4d59e-a55a-11e7-9fd3-e986d17adfdd.png)
按照你写的，把它改名放到指定目录了，但是他现在报错了，你看这是怎么回事啊
谢谢

**Comment by LiMingYuGuang** [comment]
尝试修复此问题

**Comment by LiMingYuGuang** [comment]
Fixed.
