### ISSUE TITLE
换了主题有这个错误显示在博客底部，其他主题没，我哪里做错了吗，请指点。

### ISSUE THREAD

**Issue by zhangzhichaolove** [LiMingYuGuang/typecho-theme-material#14]
Warning: array_key_exists() expects parameter 2 to be array, boolean given in /www/server/typecho/var/Typecho/Widget.php on line 379

**Comment by LiMingYuGuang** [comment]
这是个已知问题，但仍未能发现是如何产生的，因为路径为 typecho 核心，而并非主题。目前可以通过关闭 display_errors 来暂时规避此问题。
在之后的版本中将会尝试修复。

**Comment by LiMingYuGuang** [comment]
Fixed.
